services:
  database:
    restart: always
    image: mysql:8
    container_name: RCWA-backend-database
    env_file: .env
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ~/RCWA-backend/database:/var/lib/mysql

  app:
    image: node:16
    restart: always
    container_name: RCWA-backend-app
    env_file: .env
    environment:
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - database
    entrypoint: bin/bash -c
    command:
      - |
        cd /app
        npm ci
        npm run start